name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install package dependencies
        run: npm ci
      
      - name: Check linting
        run: npm run lint-check

      - name: Build application
        run: npm run build

      - name: Execute tests
        run: npm run test